[build-system]
requires = ["setuptools>=42", "wheel", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "qecc"
dynamic = ["version"]
description = "Quantum Error Correction Codes library, containing some basic functions to perform quantum LDPC decoding."
readme = "README.md"
authors = [
    {name = "Omer S. Sella", email = "o.sella@outlook.com"},
]
dependencies = [
    "numpy","scipy", "sympy", "numba", "matplotlib", "torch", "gymnasium", "ldpc", "torchrl"
]
requires-python = ">=3.8"

[tool.setuptools_scm]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "flake8",
]

[project.urls]
Homepage= "https://github.com/Omer-Sella/qecc"