from setuptools import setup
setup(name='qecc',
      version='0.1.0',
      description='Python code and notebooks to get started with quantum error correction.',
      long_description='Readable python code and accompanying explanations on beleif propagation (BP), ordered statistics decoding (OSD) and Chase-2 decoding. In addition there are some codes in compressed sparse row (CSR) format.'
      url='https://github.com/Omer-Sella/qecc',
      author='Omer S. Sella',
      author_email='o.sella@outlook.com',
      license='MIT',
      packages=['qecc'],
      instal_requires=[
          'numpy',
          'scipy',
          'copy',
          'sympy',
          'numba',
          'concurrent',
          'matplotlib',
          'sys',
          'os',
          'concurrent',
      ],
      test_suite='pytest',
      test_require=['pytest'],
      zip_safe=False)